/* ========================================================================
 * RETRO VIDEO EFFECTOR / MESSAGE ROM                              REV. 2.1
 * FILE    : STRINGS.JS
 * BANKS   : KO (KR BUTTON) / EN
 * REM     : UTF-8 STRINGS. NO REMOTE OR BUNDLED FONT FILES.
 * ======================================================================== */
var RVEText = {
    "ko": {
        "tools": "편집 도구",
        "open": "이미지 열기 (Ctrl/Command+O)",
        "export": "이미지 저장 (Ctrl/Command+S)",
        "share": "이미지 공유",
        "compare": "원본과 비교 (C)",
        "reset": "효과 초기화",
        "language": "표시 언어",
        "info": "정보",
        "close": "닫기",
        "preview": "이미지 미리보기",
        "parameters": "효과 조절",
        "local": "브라우저 내부 처리 / AI 없음",
        "dropTitle": "이미지 파일을 열어 시작하세요.",
        "dropText": "아래 작업 영역에 이미지를 끌어다 놓거나 붙여넣으세요.",
        "choose": "이미지 열기...",
        "demo": "진단용 테스트 패턴 열기",
        "dropPrivacy": "이미지는 업로드되지 않습니다.",
        "replaceImage": "새 이미지로 교체",
        "processed": "가공 이미지",
        "original": "원본 보기",
        "originalActive": "가공 보기",
        "originalShort": "원본",
        "processedShort": "가공",
        "pan": "미리보기 이동",
        "processing": "픽셀 처리 중...",
        "loading": "이미지 읽는 중",
        "fit": "화면에 맞추기 (F)",
        "zoom": "확대 배율",
        "noImage": "이미지 없음",
        "preset": "프리셋",
        "presetStandard": "기본 VHS",
        "presetSoft": "은은한 테이프",
        "presetWorn": "여러 번 복사한 테이프",
        "presetCRT": "CRT 스캔라인",
        "presetCustom": "사용자 설정",
        "seed": "노이즈 시드",
        "reseed": "새 노이즈 시드",
        "resolution": "출력 해상도",
        "resolutionNative": "원본 비율 / 최대 2560px, 4MP",
        "resolution1440": "긴 변 최대 1440px",
        "resolution720": "긴 변 최대 720px",
        "saveSettings": "설정 저장...",
        "loadSettings": "설정 열기...",
        "panelNote": "변경 즉시 자동 적용됩니다. ? 버튼을 누르면 항목별 설명이 표시됩니다.",
        "saveImage": "이미지 저장",
        "format": "파일 형식",
        "exportQuality": "저장 품질",
        "exportNote": "비교선이나 화면 UI는 저장되지 않습니다. 현재 가공된 이미지 전체를 저장합니다.",
        "download": "파일 저장",
        "privacyTitle": "01 / 브라우저 내부 처리",
        "privacyText": "Canvas와 JavaScript Web Worker로 이미지를 가공합니다. AI 모델, 외부 API, 이미지 업로드, 분석 스크립트, 원격 폰트를 사용하지 않습니다. 브라우저 저장소에는 언어 선택만 기록합니다. 이미지 공유 버튼은 파일 공유를 지원하는 환경에서만 표시하며, 사용자가 누를 때만 운영체제의 공유 기능을 호출합니다.",
        "aboutTitle": "02 / 프로그램 정보",
        "aboutText": "Retro Video Effector는 사진에 아날로그 영상 신호의 열화를 적용하는 정지 이미지 편집기입니다. Windows 95의 남색 제목줄과 입체 테두리만 사용하고 바탕 화면이나 운영체제 창은 모방하지 않습니다. 소스 주석은 C/BASIC풍이며, 실행에는 현대 브라우저가 필요합니다.",
        "limitsTitle": "03 / 지원 범위",
        "limitsText": "정지 이미지용입니다. 애니메이션은 정지 프레임으로 처리하며 움직임을 보존하지 않습니다. 투명 영역은 검정 배경에 합성합니다. 파일 최대 40MiB, 입력 최대 40MP, 출력 긴 변 최대 2560px 및 4MP입니다. HEIC·SVG·동영상은 지원하지 않습니다.",
        "keysTitle": "04 / 단축키",
        "keysText": "Ctrl/Command+O: 이미지 열기 / Ctrl/Command+S: 이미지 저장 / F: 화면 맞춤 / C: 비교 / Space 누름: 원본 / F1: 도움말 / Esc: 도움말·대화상자 닫기. 효과 탭은 방향키, Home, End로 이동할 수 있습니다.",
        "viewportHint": "드래그로 이동 · 휠/핀치로 확대 · F 화면 맞춤",
        "outputImage": "가공 이미지",
        "comparePosition": "비교 분할 위치",
        "up": "위로",
        "down": "아래로",
        "left": "왼쪽으로",
        "right": "오른쪽으로",
        "zoomIn": "확대",
        "zoomOut": "축소",
        "fileTypeError": "지원하지 않는 이미지 형식입니다. PNG, JPEG, WebP, GIF, BMP 또는 AVIF를 사용하세요.",
        "fileSizeError": "40MiB 이하의 이미지를 선택하세요.",
        "pixelLimitError": "입력 이미지는 최대 40MP, 한 변 최대 32768px까지 지원합니다.",
        "decodeError": "이미지를 읽지 못했습니다. 손상되지 않은 PNG/JPEG/WebP 파일로 다시 시도하세요.",
        "settingsError": "올바른 Retro Video Effector 설정 JSON이 아닙니다.",
        "settingsSizeError": "설정 파일은 64KiB 이하여야 합니다.",
        "settingsLoaded": "설정을 불러왔습니다.",
        "resetDone": "효과와 시드를 기본값으로 되돌렸습니다.",
        "scaledNotice": "메모리 보호를 위해 출력 이미지를 축소했습니다.",
        "saveFailed": "이미지를 저장하지 못했습니다.",
        "saved": "이미지 파일을 생성했습니다.",
        "fallbackShare": "이 환경은 파일 공유를 지원하지 않아 PNG로 저장합니다.",
        "needImage": "먼저 이미지를 선택하세요.",
        "renderFailed": "이미지 처리 중 오류가 발생했습니다.",
        "demoName": "테스트 패턴",
        "saveWorking": "파일 생성 중...",
        "stillEdition": "정지 이미지 편집기",
        "propertiesTitle": "효과 속성",
        "effectGroups": "효과 분류",
        "monitorTitle": "이미지 모니터",
        "jobTitle": "작업 설정",
        "openShort": "이미지 열기",
        "saveShort": "이미지 저장",
        "shareShort": "PNG 공유",
        "compareShort": "원본 비교",
        "resetShort": "효과 초기화",
        "demoShort": "테스트 패턴",
        "helpShort": "도움말",
        "fitShort": "화면 맞춤",
        "ok": "확인",
        "cancel": "취소",
        "previewKeys": "F: 화면 맞춤 / C: 비교 / Space: 원본",
        "tab0": "디지털",
        "tab1": "색상",
        "tab2": "신호",
        "tab3": "테이프",
        "english": "영어로 표시",
        "korean": "한국어로 표시",
        "aboutHeading": "도움말 / Retro Video Effector",
        "pngFormat": "PNG / 무손실",
        "jpegFormat": "JPEG / 압축",
        "readyStatus": "준비됨",
        "workerLabel": "워커 처리",
        "mainLabel": "메인 스레드 처리",
        "description": "Retro Video Effector - Windows 95 스타일의 로컬 이미지 편집기. AI나 업로드 없이 사진에 아날로그 테이프 효과를 적용합니다.",
        "shareFailed": "파일 공유를 열지 못했습니다. 이미지 저장 버튼으로 PNG 파일을 저장하세요.",
        "noShare": "이 브라우저는 파일 공유를 지원하지 않습니다."
    },
    "en": {
        "tools": "Editor tools",
        "open": "Open image (Ctrl/Command+O)",
        "export": "Save image (Ctrl/Command+S)",
        "share": "Share image",
        "compare": "Compare with original (C)",
        "reset": "Reset effects",
        "language": "Display language",
        "info": "Information",
        "close": "Close",
        "preview": "Image preview",
        "parameters": "Effect controls",
        "local": "Browser processing / No AI",
        "dropTitle": "Open an image file to begin.",
        "dropText": "Drop an image into the preview or paste one from your clipboard.",
        "choose": "Open image...",
        "demo": "Open diagnostic test pattern",
        "dropPrivacy": "Your image is never uploaded.",
        "replaceImage": "Replace with a new image",
        "processed": "Processed image",
        "original": "View original",
        "originalActive": "View processed",
        "originalShort": "Original",
        "processedShort": "Processed",
        "pan": "Pan preview",
        "processing": "Processing pixels...",
        "loading": "Reading image",
        "fit": "Fit to screen (F)",
        "zoom": "Zoom level",
        "noImage": "No image",
        "preset": "Preset",
        "presetStandard": "Standard VHS",
        "presetSoft": "Soft tape",
        "presetWorn": "Multi-generation tape",
        "presetCRT": "CRT scanlines",
        "presetCustom": "Custom settings",
        "seed": "Noise seed",
        "reseed": "New noise seed",
        "resolution": "Output resolution",
        "resolutionNative": "Original ratio / max 2560px, 4MP",
        "resolution1440": "Long edge up to 1440px",
        "resolution720": "Long edge up to 720px",
        "saveSettings": "Save settings...",
        "loadSettings": "Load settings...",
        "panelNote": "Changes apply automatically. Press ? for an explanation of each control.",
        "saveImage": "Save image",
        "format": "File format",
        "exportQuality": "Export quality",
        "exportNote": "The comparison divider and interface are not exported. The complete processed image is saved.",
        "download": "Save file",
        "privacyTitle": "01 / LOCAL PROCESSING",
        "privacyText": "Canvas and a JavaScript Web Worker process the image. No AI models, external APIs, image uploads, analytics, or remote fonts are used. Only your language choice is kept in browser storage. The file-share button appears only in supported browsers and calls the operating system only after you press it.",
        "aboutTitle": "02 / PROGRAM INFORMATION",
        "aboutText": "Retro Video Effector is a still-image editor that simulates analog video signal degradation. It keeps the navy title strip and beveled controls of Windows 95, without simulating a desktop or operating-system windows. C/BASIC-style comments describe code that runs in modern browsers.",
        "limitsTitle": "03 / SCOPE AND LIMITS",
        "limitsText": "Still images only. Animated files are processed as a still frame; animation is not preserved. Transparency is composited on black. Maximum file size: 40MiB. Maximum input: 40MP. Output: up to 2560px on the long edge and 4MP. HEIC, SVG, and video are not supported.",
        "keysTitle": "04 / KEYBOARD",
        "keysText": "Ctrl/Command+O: open / Ctrl/Command+S: save / F: fit / C: compare / Hold Space: original / F1: help / Esc: close help or dialog. Effect tabs support arrow keys, Home, and End.",
        "viewportHint": "Drag to pan · Wheel/pinch to zoom · F to fit",
        "outputImage": "Processed image",
        "comparePosition": "Comparison divider position",
        "up": "Up",
        "down": "Down",
        "left": "Left",
        "right": "Right",
        "zoomIn": "Zoom in",
        "zoomOut": "Zoom out",
        "fileTypeError": "Unsupported image. Use PNG, JPEG, WebP, GIF, BMP, or AVIF.",
        "fileSizeError": "Choose an image no larger than 40MiB.",
        "pixelLimitError": "Input is limited to 40MP and 32768px per side.",
        "decodeError": "Could not decode this image. Try an intact PNG, JPEG, or WebP file.",
        "settingsError": "This is not a valid Retro Video Effector settings JSON.",
        "settingsSizeError": "Settings must be no larger than 64KiB.",
        "settingsLoaded": "Settings loaded.",
        "resetDone": "Effects and seed reset to defaults.",
        "scaledNotice": "The output was resized to protect memory.",
        "saveFailed": "Could not save the image.",
        "saved": "Image file created.",
        "fallbackShare": "File sharing is not supported here. Saving a PNG instead.",
        "needImage": "Choose an image first.",
        "renderFailed": "Image processing failed.",
        "demoName": "Test pattern",
        "saveWorking": "Creating file...",
        "stillEdition": "Still image editor",
        "propertiesTitle": "Effect properties",
        "effectGroups": "Effect groups",
        "monitorTitle": "Image monitor",
        "jobTitle": "Job settings",
        "openShort": "Open image",
        "saveShort": "Save image",
        "shareShort": "Share PNG",
        "compareShort": "Compare",
        "resetShort": "Reset effects",
        "demoShort": "Test pattern",
        "helpShort": "Help",
        "fitShort": "Fit to window",
        "ok": "OK",
        "cancel": "Cancel",
        "previewKeys": "F: fit / C: compare / Space: original",
        "tab0": "Digital",
        "tab1": "Color",
        "tab2": "Signal",
        "tab3": "Tape",
        "english": "Display in English",
        "korean": "Display in Korean",
        "aboutHeading": "Help / Retro Video Effector",
        "pngFormat": "PNG / Lossless",
        "jpegFormat": "JPEG / Compressed",
        "readyStatus": "Ready",
        "workerLabel": "Worker",
        "mainLabel": "Main thread",
        "description": "Retro Video Effector - a Windows 95-style local image editor. Apply analog tape effects without AI or image uploads.",
        "shareFailed": "Could not open file sharing. Use Save image to download a PNG file.",
        "noShare": "This browser does not support file sharing."
    }
};
